// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ✅ NOW READS FROM ENVIRONMENT VARIABLES!
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. ' +
    'Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set.'
  );
}

// Extract project reference from URL for storage key
const PROJECT_REF = SUPABASE_URL.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1] || 'unknown';

// Clear old Supabase sessions from previous projects on app load
if (typeof window !== 'undefined') {
  try {
    // Clear all Supabase auth tokens from old projects
    const oldProjectRef = 'hxjomxplhbrxtqibgrxw'; // Old project reference
    const oldAuthKey = `sb-${oldProjectRef}-auth-token`;
    const oldRefreshKey = `sb-${oldProjectRef}-auth-token.refresh`;
    
    // Remove old project's auth tokens
    if (localStorage.getItem(oldAuthKey) || localStorage.getItem(oldRefreshKey)) {
      console.log('🧹 Clearing old Supabase session tokens...');
      localStorage.removeItem(oldAuthKey);
      localStorage.removeItem(oldRefreshKey);
    }
    
    // Clear any localStorage items that might be from old project
    // Supabase stores sessions with keys like: sb-<project-ref>-auth-token
    const keysToRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && key.startsWith('sb-') && !key.includes(PROJECT_REF)) {
        keysToRemove.push(key);
      }
    }
    
    if (keysToRemove.length > 0) {
      console.log(`🧹 Clearing ${keysToRemove.length} old Supabase storage keys:`, keysToRemove);
      keysToRemove.forEach(key => localStorage.removeItem(key));
    }
    
    // Log current Supabase configuration
    console.log('✅ Supabase Client Initialized:', {
      url: SUPABASE_URL,
      projectRef: PROJECT_REF,
      keyPrefix: SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...'
    });
  } catch (error) {
    console.error('Error clearing old Supabase sessions:', error);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: `sb-${PROJECT_REF}-auth-token`, // Use project-specific storage key
    storage: typeof window !== 'undefined' ? window.localStorage : undefined
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'x-application-name': 'cuephoria' // You can keep this or change to 'nerfturf'
    }
  }
});

// Helper function to log and format errors from Supabase
export const handleSupabaseError = (error: any, operation: string): string => {
  console.error(`Supabase ${operation} error:`, error);
  
  // Format the error message
  if (error.code === '23505') {
    return 'This item already exists. Please try another one.';
  } else if (error.code === '23503') {
    return 'This operation references an item that doesn\'t exist.';
  } else if (error.code === '42P01') {
    return 'Database table not found. Please contact support.';
  } else if (error.message) {
    return error.message;
  } else {
    return `Error during ${operation}. Please try again.`;
  }
};

// Helper functions for data conversion
export const convertFromSupabaseProduct = (item: any): any => {
  // Only include fields that are part of the Product type
  // Explicitly exclude database-only fields like created_at, updated_at
  const product = {
    id: item.id,
    name: item.name,
    price: item.price,
    category: item.category,
    stock: item.stock,
    image: item.image || undefined,
    originalPrice: item.original_price || undefined,
    offerPrice: item.offer_price || undefined,
    studentPrice: item.student_price || undefined,
    duration: item.duration || undefined,
    membershipHours: item.membership_hours || undefined,
    buyingPrice: item.buying_price || undefined,
    sellingPrice: item.selling_price || undefined,
    profit: item.profit || undefined
  };
  
  // Ensure we never include database timestamp fields
  // These should never be part of the Product object
  
  console.log('Converted product from DB:', product);
  return product;
};

export const convertToSupabaseProduct = (product: any, includeId: boolean = false): any => {
  // Only include fields that exist in the database schema and are defined
  const supabaseProduct: any = {};
  
  // Only include ID if explicitly requested (for inserts, not updates)
  if (includeId && product.id) {
    supabaseProduct.id = product.id;
  }
  
  // Required fields
  if (product.name !== undefined) supabaseProduct.name = product.name;
  if (product.price !== undefined) supabaseProduct.price = product.price;
  if (product.category !== undefined) supabaseProduct.category = product.category;
  if (product.stock !== undefined) supabaseProduct.stock = product.stock;
  
  // Only add optional fields if they are defined (not undefined or null)
  if (product.image !== undefined && product.image !== null) {
    supabaseProduct.image = product.image;
  }
  if (product.originalPrice !== undefined && product.originalPrice !== null) {
    supabaseProduct.original_price = product.originalPrice;
  }
  if (product.offerPrice !== undefined && product.offerPrice !== null) {
    supabaseProduct.offer_price = product.offerPrice;
  }
  if (product.studentPrice !== undefined && product.studentPrice !== null) {
    supabaseProduct.student_price = product.studentPrice;
  }
  if (product.duration !== undefined && product.duration !== null) {
    supabaseProduct.duration = product.duration;
  }
  if (product.membershipHours !== undefined && product.membershipHours !== null) {
    supabaseProduct.membership_hours = product.membershipHours;
  }
  if (product.buyingPrice !== undefined && product.buyingPrice !== null) {
    supabaseProduct.buying_price = product.buyingPrice;
  }
  if (product.sellingPrice !== undefined && product.sellingPrice !== null) {
    supabaseProduct.selling_price = product.sellingPrice;
  }
  if (product.profit !== undefined && product.profit !== null) {
    supabaseProduct.profit = product.profit;
  }
  
  // Explicitly exclude any fields that don't exist in the schema
  // The products table only has created_at, not updated_at
  // Never include: updated_at, updatedAt, created_at (for updates), createdAt
  
  console.log('Converting product to Supabase format:', supabaseProduct);
  return supabaseProduct;
};
